DROP TABLE #PedidosTemp;
DROP TABLE CLIENTES;
DROP TABLE PRODUTOS;
DROP TABLE PEDIDOS;
DROP TABLE COMPRAS;
DROP TABLE EXPEDICAO;

CREATE TABLE #PedidosTemp (
    CODIGO_PEDIDO VARCHAR(20),
    DATA_PEDIDO DATE,
    SKU VARCHAR(50),
    UPC VARCHAR(50),
    NOME_PRODUTO VARCHAR(100),
    QTD INT,
    VALOR VARCHAR(50),
    FRETE VARCHAR(50),
    EMAIL VARCHAR(100),
    CODIGO_COMPRADOR INT,
    NOME_COMPRADOR VARCHAR(100),
    ENDERECO VARCHAR(150),
    CEP VARCHAR(10),
    UF VARCHAR(2),
    PAIS VARCHAR(30)
);

BULK INSERT #PedidosTemp
FROM 'C:\5SBD\AV1\pedidos.txt'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',
    ROWTERMINATOR = '0x0a',
    CODEPAGE = '65001'
);

SELECT * FROM #PedidosTemp;

CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY,
    NOME VARCHAR(150),
    EMAIL VARCHAR(200)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT IDENTITY PRIMARY KEY,
    SKU VARCHAR(50),
    UPC VARCHAR(50),
    NOME_PRODUTO VARCHAR(150)
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO VARCHAR(50) PRIMARY KEY,
    DATA_PEDIDO DATE,
    ID_CLIENTE INT,
    VL_TOTAL DECIMAL(10,2),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE COMPRAS (
    ID_COMPRA INT IDENTITY PRIMARY KEY,
    ID_PEDIDO VARCHAR(50),
    ID_PRODUTO INT,
    QTD INT,
    VL_UNIT DECIMAL(10,2),

    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE EXPEDICAO (
    ID_EXPEDICAO INT IDENTITY PRIMARY KEY,
    ID_PEDIDO VARCHAR(50),
    ENDERECO VARCHAR(150),
    CEP VARCHAR(20),
    UF VARCHAR(10),
    PAIS VARCHAR(50),
    FRETE DECIMAL(10,2),

    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

-- COLOCANDO OS INSERTS

INSERT INTO CLIENTES (ID_CLIENTE, NOME, EMAIL)
SELECT DISTINCT
    p.CODIGO_COMPRADOR,
    p.NOME_COMPRADOR,
    p.EMAIL
FROM #PedidosTemp p
LEFT JOIN CLIENTES c
    ON c.ID_CLIENTE = p.CODIGO_COMPRADOR
WHERE c.ID_CLIENTE IS NULL;

SELECT * FROM CLIENTES;

INSERT INTO PRODUTOS (SKU, UPC, NOME_PRODUTO)
SELECT DISTINCT
    p.SKU,
    p.UPC,
    p.NOME_PRODUTO
FROM #PedidosTemp p
LEFT JOIN PRODUTOS pr
    ON pr.SKU = p.SKU
WHERE pr.SKU IS NULL;

SELECT * FROM PRODUTOS;

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE, VL_TOTAL)
SELECT DISTINCT
    p.CODIGO_PEDIDO,
    MAX(p.DATA_PEDIDO) AS DATA_PEDIDO,
    MAX(p.CODIGO_COMPRADOR) AS CODIGO_COMPRADOR,
    SUM(p.QTD * CAST(REPLACE(p.VALOR, ',', '.') AS DECIMAL(10,2))) + 
    + MAX(CAST(REPLACE(p.FRETE, ',', '.') AS DECIMAL(10,2))) AS VALOR_TOTAL
FROM #PedidosTemp p
LEFT JOIN PEDIDOS pe
    ON pe.ID_PEDIDO = p.CODIGO_PEDIDO
WHERE pe.ID_PEDIDO IS NULL
GROUP BY p.CODIGO_PEDIDO;

SELECT * FROM PEDIDOS;

INSERT INTO EXPEDICAO (ID_PEDIDO, ENDERECO, CEP, UF, PAIS, FRETE)
SELECT DISTINCT
    p.CODIGO_PEDIDO,
    p.ENDERECO,
    p.CEP,
    p.UF,
    p.PAIS,
    CAST(REPLACE(p.FRETE, ',', '.') AS DECIMAL(10,2))
FROM #PedidosTemp p
LEFT JOIN EXPEDICAO e
    ON e.ID_PEDIDO = p.CODIGO_PEDIDO
WHERE e.ID_PEDIDO IS NULL;

SELECT * FROM EXPEDICAO;

INSERT INTO COMPRAS (ID_PEDIDO, ID_PRODUTO, QTD, VL_UNIT)
SELECT
    p.CODIGO_PEDIDO,
    pr.ID_PRODUTO,
    p.QTD,
    CAST(REPLACE(p.VALOR, ',', '.') AS DECIMAL(10,2))
FROM #PedidosTemp p
INNER JOIN PRODUTOS pr
    ON p.SKU = pr.SKU
LEFT JOIN COMPRAS c
    ON c.ID_PEDIDO = p.CODIGO_PEDIDO
   AND c.ID_PRODUTO = pr.ID_PRODUTO
WHERE c.ID_COMPRA IS NULL;

SELECT * FROM COMPRAS;
