DROP TABLE #PedidosTemp;
DROP TABLE COMPRAS;
DROP TABLE EXPEDICAO;
DROP TABLE PEDIDOS;
DROP TABLE CLIENTES;
DROP TABLE ESTOQUE;
DROP TABLE PRODUTOS;

CREATE TABLE #PedidosTemp (
    CODIGO_PEDIDO    VARCHAR(20),
    DATA_PEDIDO      DATE,
    SKU              VARCHAR(50),
    UPC              VARCHAR(50),
    NOME_PRODUTO     VARCHAR(100),
    QTD              INT,
    VALOR            VARCHAR(50),
    FRETE            VARCHAR(50),
    EMAIL            VARCHAR(100),
    CODIGO_COMPRADOR INT,
    NOME_COMPRADOR   VARCHAR(100),
    ENDERECO         VARCHAR(150),
    CEP              VARCHAR(10),
    UF               VARCHAR(2),
    PAIS             VARCHAR(30),
    QTD_ESTOQUE      INT           
);

BULK INSERT #PedidosTemp
FROM 'C:\5SBD\AV1\pedidos2.txt'
WITH (
    FIRSTROW        = 2,
    FIELDTERMINATOR = ';',
    ROWTERMINATOR   = '0x0a',
    CODEPAGE        = '65001'
);

SELECT * FROM #PedidosTemp;

CREATE TABLE CLIENTES (
    ID_CLIENTE INT          PRIMARY KEY,
    NOME       VARCHAR(150),
    EMAIL      VARCHAR(200)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO   INT IDENTITY PRIMARY KEY,
    SKU          VARCHAR(50),
    UPC          VARCHAR(50),
    NOME_PRODUTO VARCHAR(150)
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO   VARCHAR(50)  PRIMARY KEY,
    DATA_PEDIDO DATE,
    ID_CLIENTE  INT,
    VL_TOTAL    DECIMAL(10,2),
    STATUS      VARCHAR(20)  NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE COMPRAS (
    ID_COMPRA  INT IDENTITY PRIMARY KEY,
    ID_PEDIDO  VARCHAR(50),
    ID_PRODUTO INT,
    QTD        INT,
    VL_UNIT    DECIMAL(10,2),
    FOREIGN KEY (ID_PEDIDO)  REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE EXPEDICAO (
    ID_EXPEDICAO INT IDENTITY PRIMARY KEY,
    ID_PEDIDO    VARCHAR(50),
    ENDERECO     VARCHAR(150),
    CEP          VARCHAR(20),
    UF           VARCHAR(10),
    PAIS         VARCHAR(50),
    FRETE        DECIMAL(10,2),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

CREATE TABLE ESTOQUE (
    ID_PRODUTO  INT PRIMARY KEY,
    QTD_ESTOQUE INT NOT NULL DEFAULT 0,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

-- cargas

INSERT INTO CLIENTES (ID_CLIENTE, NOME, EMAIL)
SELECT DISTINCT
    p.CODIGO_COMPRADOR,
    p.NOME_COMPRADOR,
    p.EMAIL
FROM #PedidosTemp p
LEFT JOIN CLIENTES c ON c.ID_CLIENTE = p.CODIGO_COMPRADOR
WHERE c.ID_CLIENTE IS NULL;

SELECT * FROM CLIENTES;

INSERT INTO PRODUTOS (SKU, UPC, NOME_PRODUTO)
SELECT DISTINCT
    p.SKU,
    p.UPC,
    p.NOME_PRODUTO
FROM #PedidosTemp p
LEFT JOIN PRODUTOS pr ON pr.SKU = p.SKU
WHERE pr.SKU IS NULL;

SELECT * FROM PRODUTOS;

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE, VL_TOTAL, STATUS)
SELECT DISTINCT
    p.CODIGO_PEDIDO,
    MAX(p.DATA_PEDIDO),
    MAX(p.CODIGO_COMPRADOR),
    SUM(p.QTD * CAST(REPLACE(p.VALOR, ',', '.') AS DECIMAL(10,2)))
        + MAX(CAST(REPLACE(p.FRETE, ',', '.') AS DECIMAL(10,2))),
    NULL
FROM #PedidosTemp p
LEFT JOIN PEDIDOS pe ON pe.ID_PEDIDO = p.CODIGO_PEDIDO
WHERE pe.ID_PEDIDO IS NULL
GROUP BY p.CODIGO_PEDIDO;

SELECT * FROM PEDIDOS;

INSERT INTO EXPEDICAO (ID_PEDIDO, ENDERECO, CEP, UF, PAIS, FRETE)
SELECT DISTINCT
    p.CODIGO_PEDIDO,
    p.ENDERECO,
    p.CEP,
    p.UF,
    p.PAIS,
    CAST(REPLACE(p.FRETE, ',', '.') AS DECIMAL(10,2))
FROM #PedidosTemp p
LEFT JOIN EXPEDICAO e ON e.ID_PEDIDO = p.CODIGO_PEDIDO
WHERE e.ID_PEDIDO IS NULL;

SELECT * FROM EXPEDICAO;

INSERT INTO COMPRAS (ID_PEDIDO, ID_PRODUTO, QTD, VL_UNIT)
SELECT
    p.CODIGO_PEDIDO,
    pr.ID_PRODUTO,
    p.QTD,
    CAST(REPLACE(p.VALOR, ',', '.') AS DECIMAL(10,2))
FROM #PedidosTemp p
INNER JOIN PRODUTOS pr ON p.SKU = pr.SKU
LEFT JOIN COMPRAS c
    ON c.ID_PEDIDO = p.CODIGO_PEDIDO AND c.ID_PRODUTO = pr.ID_PRODUTO
WHERE c.ID_COMPRA IS NULL;

SELECT * FROM COMPRAS;

INSERT INTO ESTOQUE (ID_PRODUTO, QTD_ESTOQUE)
SELECT
    pr.ID_PRODUTO,
    MAX(p.QTD_ESTOQUE)
FROM #PedidosTemp p
INNER JOIN PRODUTOS pr ON pr.SKU = p.SKU
LEFT JOIN ESTOQUE e ON e.ID_PRODUTO = pr.ID_PRODUTO
WHERE e.ID_PRODUTO IS NULL
GROUP BY pr.ID_PRODUTO;

SELECT 
       e.ID_PRODUTO, pr.NOME_PRODUTO, e.QTD_ESTOQUE
FROM ESTOQUE e
INNER JOIN PRODUTOS pr ON pr.ID_PRODUTO = e.ID_PRODUTO;

-- cursor da ativid 2

DECLARE
    @V_IDPEDIDO       VARCHAR(50),
    @V_IDPRD      INT,
    @V_QTDCOMPRA    INT,
    @V_QTDESTOQ     INT,
    @V_PEDIATEND  INT;

DECLARE C_ATIVIDADE CURSOR FOR
    SELECT ID_PEDIDO
    FROM PEDIDOS
    WHERE STATUS IS NULL
    ORDER BY DATA_PEDIDO;

OPEN C_ATIVIDADE;
FETCH NEXT FROM C_ATIVIDADE INTO @V_IDPEDIDO;

WHILE @@FETCH_STATUS = 0
BEGIN

    SET @V_PEDIATEND = 1;

    DECLARE C_ITENS CURSOR FOR
        SELECT c.ID_PRODUTO, c.QTD
        FROM COMPRAS c
        WHERE c.ID_PEDIDO = @V_IDPEDIDO;

    OPEN C_ITENS;
    FETCH NEXT FROM C_ITENS INTO @V_IDPRD, @V_QTDCOMPRA;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        SELECT @V_QTDESTOQ = QTD_ESTOQUE
        FROM ESTOQUE
        WHERE ID_PRODUTO = @V_IDPRD;

        IF @V_QTDESTOQ < @V_QTDCOMPRA
        BEGIN
            SET @V_PEDIATEND = 0;
            PRINT 'Pedido ' + @V_IDPEDIDO
                + ': estoque insuficiente para produto ID ' + CAST(@V_IDPRD AS VARCHAR)
                + ' (estoque=' + CAST(@V_QTDESTOQ AS VARCHAR)
                + ', necessario=' + CAST(@V_QTDCOMPRA AS VARCHAR) + ')';
        END;

        FETCH NEXT FROM C_ITENS INTO @V_IDPRD, @V_QTDCOMPRA;
    END;

    CLOSE C_ITENS;
    DEALLOCATE C_ITENS;

    IF @V_PEDIATEND = 1
    BEGIN
        UPDATE ESTOQUE
        SET QTD_ESTOQUE = QTD_ESTOQUE - c.QTD
        FROM ESTOQUE est
        INNER JOIN COMPRAS c ON c.ID_PRODUTO = est.ID_PRODUTO
        WHERE c.ID_PEDIDO = @V_IDPEDIDO;

        UPDATE PEDIDOS SET STATUS = 'Atendido' WHERE ID_PEDIDO = @V_IDPEDIDO;

        PRINT 'Pedido ' + @V_IDPEDIDO + ': ATENDIDO - estoque debitado.';
    END
    ELSE
    BEGIN
        UPDATE PEDIDOS SET STATUS = 'Pendente' WHERE ID_PEDIDO = @V_IDPEDIDO;

        PRINT 'Pedido ' + @V_IDPEDIDO + ': PENDENTE - estoque insuficiente.';
    END;

    FETCH NEXT FROM C_ATIVIDADE INTO @V_IDPEDIDO;
END;

CLOSE C_ATIVIDADE;
DEALLOCATE C_ATIVIDADE;

-- pedido apos o cursor
SELECT 
       ID_PEDIDO, DATA_PEDIDO, VL_TOTAL, STATUS
FROM PEDIDOS
ORDER BY DATA_PEDIDO;

-- estoque apos cursor
SELECT 
       e.ID_PRODUTO, pr.NOME_PRODUTO, e.QTD_ESTOQUE AS QTD_RESTANTE
FROM ESTOQUE e
INNER JOIN PRODUTOS pr ON pr.ID_PRODUTO = e.ID_PRODUTO;

-- Resumo
SELECT
    pe.ID_PEDIDO,
    pe.STATUS,
    pr.NOME_PRODUTO,
    c.QTD         AS QTD_COMPRADA,
    e.QTD_ESTOQUE AS ESTOQUE_RESTANTE
FROM PEDIDOS pe
INNER JOIN COMPRAS  c  ON c.ID_PEDIDO   = pe.ID_PEDIDO
INNER JOIN PRODUTOS pr ON pr.ID_PRODUTO = c.ID_PRODUTO
INNER JOIN ESTOQUE  e  ON e.ID_PRODUTO  = pr.ID_PRODUTO
ORDER BY pe.DATA_PEDIDO, pr.NOME_PRODUTO;
