DROP TABLE IF EXISTS #CARGA_CARG;
DROP TABLE IF EXISTS #ENTREGA_ENT;
DROP TABLE IF EXISTS MOVIMENTO_MOV;
DROP TABLE IF EXISTS COMPRAS_COM;
DROP TABLE IF EXISTS ITPEDIDO_ITP;
DROP TABLE IF EXISTS PEDIDOS_PED;
DROP TABLE IF EXISTS CLIENTES_CLI;
DROP TABLE IF EXISTS PRODUTOS_PRD;

CREATE TABLE #CARGA_CARG (
    ORDER_ID VARCHAR(50),
    ORDER_ITEM_ID VARCHAR(50),
    PURCHASE_DATE DATETIME,
    PAYMENTS_DATE DATETIME,
    BUYER_EMAIL VARCHAR(150),
    BUYER_NAME VARCHAR(150),
    CPF VARCHAR(14),
    BUYER_PHONE_NUMBER VARCHAR(20),
    SKU VARCHAR(50),
    UPC VARCHAR(50),
    PRODUCT_NAME VARCHAR(200),
    QUANTITY_PURCHASED INT,
    CURRENCY VARCHAR(10),
    ITEM_PRICE DECIMAL(10,2),
    SHIP_SERVICE_LEVEL VARCHAR(100),
    SHIP_ADDRESS_1 VARCHAR(200),
    SHIP_ADDRESS_2 VARCHAR(200),
    SHIP_ADDRESS_3 VARCHAR(200),
    SHIP_CITY VARCHAR(100),
    SHIP_STATE VARCHAR(50),
    SHIP_POSTAL_CODE VARCHAR(20),
    SHIP_COUNTRY VARCHAR(50)
);

BULK INSERT #CARGA_CARG
FROM 'C:\5SBD\AV1\TESTE.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',
    CODEPAGE = '65001'
);

SELECT * FROM #CARGA_CARG;

-- tabela de carga pelos fornecedores
/*
CREATE TABLE #ENTREGA_ENT (
    SKU VARCHAR(50),
    QTD INT
);

BULK INSERT #ENTREGA_ENT
FROM 'C:\5SBD\AV1\TESTE_FORNECEDOR.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',
    CODEPAGE = '65001'
);

SELECT * FROM #ENTREGA_ENT;

UPDATE p
SET p.QTD_ESTOQUE = p.QTD_ESTOQUE + E.QTD_ENTREGUE
FROM PRODUTOS_PRD p
INNER JOIN #ENTREGA_ENT E
    ON p.SKU = E.SKU;

SELECT * FROM PRODUTOS_PRD;

*/


CREATE TABLE CLIENTES_CLI (
    ID_CLIENTE INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(150),
    EMAIL VARCHAR(150),
    CPF VARCHAR(14),
    TELEFONE VARCHAR(20)
);

CREATE TABLE PRODUTOS_PRD (
    ID_PRODUTO INT IDENTITY PRIMARY KEY,
    SKU VARCHAR(50),
    UPC VARCHAR(50),
    NOME_PRODUTO VARCHAR(200),
    QTD_ESTOQUE INT DEFAULT 0
);

CREATE TABLE PEDIDOS_PED (
    ID_PEDIDO VARCHAR(50) PRIMARY KEY,
    DATA_PEDIDO DATETIME,
    ID_CLIENTE INT,
    VL_TOTAL DECIMAL(10,2),
    STATUS VARCHAR(20),

    FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES_CLI(ID_CLIENTE)
);

CREATE TABLE ITPEDIDO_ITP (
    ID_ITEM INT IDENTITY PRIMARY KEY,
    ID_PEDIDO VARCHAR(50),
    ID_PRODUTO INT,
    QTD INT,
    VL_UNIT DECIMAL(10,2),

    FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDOS_PED(ID_PEDIDO),

    FOREIGN KEY (ID_PRODUTO)
        REFERENCES PRODUTOS_PRD(ID_PRODUTO)
);

CREATE TABLE MOVIMENTO_MOV (
    ID_MOVIMENTO INT IDENTITY PRIMARY KEY,
    ID_PEDIDO VARCHAR(50),
    ID_PRODUTO INT,
    QTD_MOVIMENTADA INT,
    ESTOQUE_ANTES INT,
    ESTOQUE_DEPOIS INT,
    DATA_MOVIMENTO DATETIME DEFAULT GETDATE()
);

CREATE TABLE COMPRAS_COM (
    ID_COMPRA INT IDENTITY PRIMARY KEY,
	ID_PEDIDO VARCHAR(50),
    ID_PRODUTO INT,
    QTD_SOLICITADA INT,
    DATA_SOLICITACAO DATETIME DEFAULT GETDATE(),
	
	FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS_PED(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS_PRD(ID_PRODUTO)
);

INSERT INTO CLIENTES_CLI (NOME, EMAIL, CPF, TELEFONE)
SELECT DISTINCT
    c.BUYER_NAME,
    c.BUYER_EMAIL,
    c.CPF,
    c.BUYER_PHONE_NUMBER
FROM #CARGA_CARG c
LEFT JOIN CLIENTES_CLI cli
    ON cli.EMAIL = c.BUYER_EMAIL
WHERE cli.EMAIL IS NULL;

SELECT * FROM CLIENTES_CLI;

INSERT INTO PRODUTOS_PRD (
    SKU,
    UPC,
    NOME_PRODUTO,
    QTD_ESTOQUE
)
SELECT DISTINCT
    c.SKU,
    c.UPC,
    c.PRODUCT_NAME,
    100
FROM #CARGA_CARG c
LEFT JOIN PRODUTOS_PRD p
    ON p.SKU = c.SKU
WHERE p.SKU IS NULL;


SELECT * FROM PRODUTOS_PRD;

INSERT INTO PEDIDOS_PED (
    ID_PEDIDO,
    DATA_PEDIDO,
    ID_CLIENTE,
    VL_TOTAL,
    STATUS
)
SELECT DISTINCT
    c.ORDER_ID,
    MAX(c.PURCHASE_DATE),
    MAX(cli.ID_CLIENTE),
    SUM(c.QUANTITY_PURCHASED * c.ITEM_PRICE),
    NULL
FROM #CARGA_CARG c
INNER JOIN CLIENTES_CLI cli
    ON cli.EMAIL = c.BUYER_EMAIL
LEFT JOIN PEDIDOS_PED ped
    ON ped.ID_PEDIDO = c.ORDER_ID
WHERE ped.ID_PEDIDO IS NULL
GROUP BY c.ORDER_ID;

SELECT * FROM #CARGA_CARG;
SELECT * FROM PEDIDOS_PED;

INSERT INTO ITPEDIDO_ITP (
    ID_PEDIDO,
    ID_PRODUTO,
    QTD,
    VL_UNIT
)
SELECT DISTINCT
    c.ORDER_ID,
    p.ID_PRODUTO,
    c.QUANTITY_PURCHASED,
    c.ITEM_PRICE
FROM #CARGA_CARG c
INNER JOIN PRODUTOS_PRD p
    ON p.SKU = c.SKU
LEFT JOIN ITPEDIDO_ITP it
    ON it.ID_PEDIDO = c.ORDER_ID
   AND it.ID_PRODUTO = p.ID_PRODUTO
WHERE it.ID_ITEM IS NULL;

SELECT * FROM #CARGA_CARG;
SELECT * FROM ITPEDIDO_ITP;


-- CURSOR
GO
CREATE OR ALTER PROCEDURE PRC_AV1
AS
BEGIN

DECLARE
    @V_IDPEDIDO VARCHAR(50),
    @V_IDPRD INT,
    @V_QTD INT,
    @V_ESTOQUE INT,
    @V_ATENDER INT;

DECLARE C_PEDIDOS CURSOR FOR
    SELECT ID_PEDIDO
    FROM PEDIDOS_PED
    WHERE STATUS IS NULL
    ORDER BY VL_TOTAL DESC, DATA_PEDIDO ASC;

OPEN C_PEDIDOS;
FETCH NEXT FROM C_PEDIDOS INTO @V_IDPEDIDO;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @V_ATENDER = 1;

    DECLARE C_ITENS CURSOR FOR
        SELECT ID_PRODUTO, QTD
        FROM ITPEDIDO_ITP
        WHERE ID_PEDIDO = @V_IDPEDIDO;

    OPEN C_ITENS;
    FETCH NEXT FROM C_ITENS INTO @V_IDPRD, @V_QTD;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        SELECT @V_ESTOQUE = QTD_ESTOQUE
        FROM PRODUTOS_PRD
        WHERE ID_PRODUTO = @V_IDPRD;

        IF @V_ESTOQUE < @V_QTD
        BEGIN
            SET @V_ATENDER = 0;

            INSERT INTO COMPRAS_COM(
				ID_PEDIDO,
                ID_PRODUTO,
                QTD_SOLICITADA
            )
            VALUES (
				@V_IDPEDIDO,
                @V_IDPRD,
                @V_QTD
            );
        END

        FETCH NEXT FROM C_ITENS INTO @V_IDPRD, @V_QTD;
    END

    CLOSE C_ITENS;
    DEALLOCATE C_ITENS;

IF @V_ATENDER = 1
BEGIN

    INSERT INTO MOVIMENTO_MOV (
        ID_PEDIDO,
        ID_PRODUTO,
        QTD_MOVIMENTADA,
        ESTOQUE_ANTES,
        ESTOQUE_DEPOIS
    )
    SELECT
        i.ID_PEDIDO,
        i.ID_PRODUTO,
        i.QTD,
        p.QTD_ESTOQUE,
        p.QTD_ESTOQUE - i.QTD
    FROM ITPEDIDO_ITP i
    INNER JOIN PRODUTOS_PRD p
        ON p.ID_PRODUTO = i.ID_PRODUTO
    WHERE i.ID_PEDIDO = @V_IDPEDIDO;

    UPDATE p
    SET p.QTD_ESTOQUE = p.QTD_ESTOQUE - i.QTD
    FROM PRODUTOS_PRD p
    INNER JOIN ITPEDIDO_ITP i
        ON p.ID_PRODUTO = i.ID_PRODUTO
    WHERE i.ID_PEDIDO = @V_IDPEDIDO;

    UPDATE PEDIDOS_PED
    SET STATUS = 'ATENDIDO'
    WHERE ID_PEDIDO = @V_IDPEDIDO;

END
    ELSE
    BEGIN
        UPDATE PEDIDOS_PED
        SET STATUS = 'PENDENTE'
        WHERE ID_PEDIDO = @V_IDPEDIDO;
    END

    FETCH NEXT FROM C_PEDIDOS INTO @V_IDPEDIDO;
END

CLOSE C_PEDIDOS;
DEALLOCATE C_PEDIDOS;
END;
GO

EXEC PRC_AV1;

SELECT * FROM PEDIDOS_PED ORDER BY VL_TOTAL DESC;
SELECT * FROM MOVIMENTO_MOV ORDER BY DATA_MOVIMENTO;
SELECT * FROM COMPRAS_COM ORDER BY DATA_SOLICITACAO;
SELECT * FROM PRODUTOS_PRD;
